documentation
readMeV005
	^'	
FIX:
------
- MessageNotUndestood>>UndefindObject>>visible.
- freeze on click [DRAW PROFILE].
- Missing cross cursor.
- [ENTERTEXT] illigal color.

ADD FUTURE:
---------------------
- Sensor location Morph defalts now StringMorph wthout BorderdStringMorph.
turn to original appearance:

 GdsFeelMorphic borderedSensorDisplay: true.

- display fitting ratio control.
 defaut is 0.98.
 between 0.5 and 1.0. 

 GdsFeelMorphic fittingRatio: 0.8.

rectangular rubberband enhance:
------------------------------------------------
- reference point.
- delta size, length.
 W: ##.# H: ##.# L: ##.#
- snaped sensor point.

tool palette layout:
----------------------------
- separate ''digitizing tools''.

'
