as yet unclassified
favaritMonoSpaceFamilyNames
	"specify only ttf. can't specify ttc".
	"  key: familyName"
	"value: nameWithoutExtension"
	^ {'FreeMono'->'FreeMono' . 'Bitstream Vera Sans Mono'->'VeraMono' . 'Osaka'->'OsakaMono' . 'MS Gothic'->'MS Gothic' . 'IPAGothic'->'ipag'}.
	"^ { 'IPAGothic'->'ipag' . 'MS UI Gothic'->'msgothic' . 'FreeMono'->'FreeMono' . 'Bitstream Vera Sans Mono'->'VeraMono' .}"